// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {dharmas} from '../models';
import {uuid} from '../models';

export function CreateDharma(arg1:string):Promise<dharmas.Dharmas>;

export function DeleteDharma(arg1:uuid.UUID):Promise<void>;

export function GetDharmaByID(arg1:uuid.UUID):Promise<dharmas.Dharmas>;

export function ListAllDharmas():Promise<Array<dharmas.Dharmas>>;
