// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateDharma(arg1) {
  return window['go']['dharmas']['DharmaAppService']['CreateDharma'](arg1);
}

export function DeleteDharma(arg1) {
  return window['go']['dharmas']['DharmaAppService']['DeleteDharma'](arg1);
}

export function GetDharmaByID(arg1) {
  return window['go']['dharmas']['DharmaAppService']['GetDharmaByID'](arg1);
}

export function ListAllDharmas() {
  return window['go']['dharmas']['DharmaAppService']['ListAllDharmas']();
}
