// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateTask(arg1) {
  return window['go']['tasks']['TaskService']['CreateTask'](arg1);
}

export function DeleteTask(arg1) {
  return window['go']['tasks']['TaskService']['DeleteTask'](arg1);
}

export function FindTaskByID(arg1) {
  return window['go']['tasks']['TaskService']['FindTaskByID'](arg1);
}

export function FindTasksByDharmaID(arg1) {
  return window['go']['tasks']['TaskService']['FindTasksByDharmaID'](arg1);
}
