// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {tasks} from '../models';
import {uuid} from '../models';

export function CreateTask(arg1:tasks.Task):Promise<tasks.Task>;

export function DeleteTask(arg1:uuid.UUID):Promise<void>;

export function FindTaskByID(arg1:uuid.UUID):Promise<tasks.Task>;

export function FindTasksByDharmaID(arg1:uuid.UUID):Promise<Array<tasks.Task>>;
